version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: smart_productivity_postgres
    environment:
      POSTGRES_DB: productivity
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro

volumes:
  pg_data:
